### ISSUE TITLE
Bug: Smoke2 test failing

### ISSUE THREAD

**Issue by Puciek** [bbqsrc/gherkin-rust#13]
Fresh checkout of master, trying to run the tests - one of the smokes is failing:

```
PS F:\work\RustProjects\gherkin-rust> cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.16s
     Running target\debug\deps\gherkin_rust-9b6b434a8d9b6c63.exe

running 12 tests
test tagexpr::tests::parse_tag_expr1 ... ok
test tagexpr::tests::parse_tag_expr3 ... ok
test tagexpr::tests::parse_tag_expr1b ... ok
test tagexpr::tests::parse_tag_expr2 ... ok
test tagexpr::tests::parse_tag_expr4 ... ok
test tagexpr::tests::parse_tag_expr2b ... ok
test tagexpr::tests::parse_tag_expr5 ... ok
test tagexpr::tests::parse_tag_expr6 ... ok
test tagexpr::tests::parse_tag_expr7 ... ok
test parser::test::smoke2 ... FAILED
test parser::test::smoke ... ok
test tagexpr::tests::parse_tag_expr8 ... ok

failures:

---- parser::test::smoke2 stdout ----
thread 'parser::test::smoke2' panicked at 'assertion failed: gherkin_parser::feature(&s, &env).is_ok()', src\parser.rs:515:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    parser::test::smoke2

test result: FAILED. 11 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by bbqsrc** [comment]
Haha, damn it. Let me check.

**Comment by bbqsrc** [comment]
I had one commit where I made clippy stop complaining that I hadn't pushed so pushed that now, but it passes for me. I see you're doing this on Windows, it's probably line ending handling (I have only cared about "\n" right now.

**Comment by Puciek** [comment]
Oh, that could do it. I might as well look forward to fixing it, as line handling I should do - trying to understand the smoke2 magic is beyond me.

**Comment by bbqsrc** [comment]
I've just checked on my Windows PC, and didn't fail. When I forced the test.feature to be CRLF it fails, so I'll fix it, won't take long.

**Comment by bbqsrc** [comment]
Okay should be fixed in the most recent commit. If you find any other issues in the grammar just let me know and I'll fix them quickly.

**Comment by Puciek** [comment]
Sorted! Cheers :D
