### ISSUE TITLE
The grammar doesn't handle empty table headers though those seem to be supported?

### ISSUE THREAD

**Issue by ahmedcharles** [bbqsrc/gherkin-rust#3]
https://github.com/cucumber/cucumber/tree/master/datatable has examples with empty table headers.

**Comment by bbqsrc** [comment]
Yup, just the simplest implementation right now.

https://github.com/cucumber/cucumber/tree/master/datatable#for-contributors

Patches absolutely welcome. 😄 👍

**Comment by ahmedcharles** [comment]
The features I have which originally lead me to file this now parse with the latest github branches, thanks. Now I just wait for the next release. :)

**Comment by bbqsrc** [comment]
Published v0.6.0. :)
